version: '3.9'
services:
  hazelcast:
    container_name: hazelcast
    ports:
      - '5701:5701'
    image: 'hazelcast/hazelcast:5.4.0'
    environment:
      HZ_JET_ENABLED: 'true'
      HZ_JET_RESOURCEUPLOADENABLED: 'true'
  
  # http://localhost:9090
  management-center:
    image: 'hazelcast/management-center:5.4.0'
    ports:
      - "9090:8080"
    environment:
      - MC_DEFAULT_CLUSTER=dev
      - MC_DEFAULT_CLUSTER_MEMBERS=hazelcast
